sudo: required
services:
- docker
before_install:
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- openssl aes-256-cbc -K $encrypted_e2a53ddc64a6_key -iv $encrypted_e2a53ddc64a6_iv
  -in id_rsa.enc -out ./id_rsa -d
- docker build nginx -t theskeleton-webserver
- docker ps -a
script:
- docker tag theskeleton-webserver:latest $DOCKER_HUB_USERNAME/theskeleton-webserver:production
- docker push $DOCKER_HUB_USERNAME/theskeleton-webserver:production
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 id_rsa && ssh -o StrictHostKeyChecking=no -i ./id_rsa docker@52.187.120.141
    './deploy.sh'
  on:
    branch: master
env:
  global:
  - secure: XrfeMNYHtKpWcEUchae3y2PoTjZVcXamcPxtp085FJ8S25Xa2CRrClzALdfF+tF9ruzJP4uXOmv2X5pjwZtqnOPoHRUzRHiDSf+ElOrIA40gBNTBul79aH8JnABCUng2vc3UIo8WbAqAW1b6yhA17AuEctmLYfWcv4j7xPa3/PFKKEft2QRHZuUcA/gFnr50SuK7x5t6Lf1t5WRU/Fh5w1VJWOhg/u7lEDLia/HW0qkchr29uRh/2aYbcubUagtdlh3srJnGlE1bHWjBRoaczRyS3K4aDQ8lixbHOw/DpYwlNq7CYLIB4PYqGcq5souPaZg1jep7xHfS34Oq+g74u7EpNB4yG5EpogP4S1IlVCam22UHImjotGwwcPPaxYH2WjkyTS0k7Se67nlvUnc/pZltRWHfaHtrY44Mf6Ug2MhFdgmq+q1MdjHTwh2+79O1dmwkELTiQjqHnOKrBYuukrTuNCGDdE8uSZ1qsDzQgWFAEM0szq0/lt132j9UGJH5mhbnj4esLBF0/xFwIORqqDZIrkkaDUzK9Wlc3z5CvJ5zB6oaqf+dChwIVWCrnYJbIFOL5G9922TQ4tu0N1LkumiKugsa908z/FigOmoJ7Xg8mekVAySamXqlrjA9gwKA6td3o+bDTiPAkoyFhNxs+c39aoHRgjyQwE8/hJ6QtA0=
  - secure: MXUoLErJyo28nk4eB1vyO2xnde2N2/7radgROjs6eJDrb0djLWcV09gnbj4J/f8MBidIfNgJBKUc8QmWwG+gOAWFFn9xgLqsysOlR6NruOB3ni4IXQ5Fhwm0KpXrmDbkhb6WyoJjAOgvMzau70eWCgT1qpxotlhGWmuSrwPGC34cHppr0uIMR7w+jDF8X2gjxNFD7TidLtQ3mMf/eEM4iKgN5+avLMnjIOdGPSZT1h3PPRLhClIYtXFBnP387hQyCjRWTz6zgQl+5seJioaHsSZ7kfj1clR1OrgFP1DzWdCmYTfFxrbv9eTKtF/Zxn2Ohph0RSmtE57FLTrTnZpw1dM8EIm5QDKDlOXzrjV/o7JzMYjp+sb3ClUTarNUY2Fv2XYKdLBDFkTe++NwfPCcah+1MUvDmGKgSTEAft4fDu2GHpRHMR4z6osnGgB834GTcg+MXyUfhgX09pRDjJrZLGPif4JWV9OLaNUOE417OA4w+L5rMDIAawTuVIboBpUzzdugaGLrV0Jcye3bTPGkIwvFgKaoWx4UJpNe6tPe4Iv3XOd6ArcF6Wo6Vzz3KM18L33loMI6wlJP6srBvyT8rWFZOOUaF22xIJ7Sfv5YJU7ecuNcVD5dzuaSCFS/+6hK8Z7wFSUoEGthey/KDEz8AbsS7WDuipgh3GjsPZLxR38=
  - secure: ReeoceO4I7u0p1ghkAQHfgD/HDBNc1SIz+ETCVTvDE/E0I9RxjfxPlnUhWxxuoQikKHwES+gdLR+0ZrThaSLOUyWrNFAUeUePQY8rNMOtzVQYIOrjOUp484NJdZxSG3DrU8kuCQzndQCUT7LYVVDsseiaUdpguOwNqb6yPPjFv/ByZUyUaNaYTt5+1xRcMVfWkNkv+Ib02hGg1S6KMDJvxqS3BPYVTd+Ty5ZQ1vSElIxyxxmT0rFVRvyVx80sQ0+DXWlz1S6l8fUqxusdR1AUrrrIM8g4KfI/IG+v38AHEss4O/23j89k0kTrAQ3TqBrGjthMXA7oXy3CuU+F7VVgm9f6AGvNv6Wkg39llTlFkNAXaUeV8EeEcP/ACvXE5Bel18IvY+KxprBekJr3SBBElasW6hCbtYf9WPm16K9c2vgChzou1tzcEl8iCRhcZS5jrRExIg2LIjFWu4lwp4qNGyftvGZm+RBG1RPGISip84+jeja1WWtvVVgJwtJUrImiSpJIEo02qp77M/+REHm3U40B/bKlFb1Txe7nPOXMHcc9fWHJPmsRFvW2l4w3wrtt3hxn0rHFpyUhFdB7LwiTWglwHRx7BEjkG5pFMdeQZW2ruwgrljVFlRo2Jim7LqsjkXoxpcmTZjG+c7rowALgFVwY2/ssqd9fMo857jPplA=